[program:liquidsoap]
command=/usr/local/bin/liquidsoap /var/azuracast/stations/%(program_name)s/config/liquidsoap.liq
process_name=%(program_name)s_%(process_num)s
numprocs=1
autostart=true
autorestart=true
user=azuracast
redirect_stderr=true
stdout_logfile=/var/azuracast/stations/%(program_name)s/config/liquidsoap.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=5