# Listen on all network interfaces.
bind 0.0.0.0

# Disable persistence, as this is a cache.
save ""
appendonly no

# Set a reasonable memory limit and eviction policy.
maxmemory 128mb
maxmemory-policy allkeys-lru

# Be quiet.
always-show-logo no